Repository eccentriccoder01/Venturalink, pull requests merged in 2025-10, with the labels that each got.

#134 Refactor navbar styles by creating separate CSS file
  about.html
  blog.html
  contact.html
  features.html
  guides.html
  help.html
  pricing.html
  styles/navbar.css
  terms.html
Labels: gssoc25, level 2

#147 Added cicd pipeline
  .github/workflows/deploy.yml
Labels: enhancement, gssoc25, level 3

#165 Fix: Updated footer links in features.html to avoid broken/missing pages
  features.html
Labels: gssoc25, level 3

#156 Fixed Uneven footer spacing on contact.html , feature.html and pricing.html pages
  contact.html
  features.html
  pricing.html
Labels: bug, gssoc25, level 2

#171 Add logout confirmation modal with glass style
  login.html
  package-lock.json
  package.json
  profile.html
  scripts/firebase.js
  scripts/login.js
  scripts/profile.js
  scripts/register.js
  server.js
  styles/auth.css
  styles/profile.css
Labels: gssoc25, level 2

#177 Enhance ‘Go to Top’ Button with Themed Rocket Animation
  features.html
  index.html
  scripts/main.js
  styles/mainindex.css
Labels: gssoc25, level 1

#163 Improve textarea and select styling in proposal.css
  styles/proposal.css
Labels: gssoc25, level 3

#180 [Feature] - Added a Dynamic glowing progress bar for signup page
  .gitignore
  login.html
  register.html
  scripts/register.js
Labels: enhancement, good first issue, gssoc25, level 2, hacktoberfest-accepted

#168 Fixed light theme support for cookie policy page
  cookies.html
Labels: gssoc25, level 2
