Repository eccentriccoder01/Venturalink, pull requests merged in 2025-09, with the labels that each got.

#23 select your role option is removed and placed as a placeholder
  register.html
  styles/auth.css
Labels: good first issue, gssoc25, level 1

#34 Enhanced Code of Conduct with Badges, Emojis, GIFs, and Contributor Wall ✨
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, gssoc25, level 1

#46 ISSUE 11 PR about us page
  about.html
  index.html
Labels: enhancement, gssoc25, level 3

#47 Add features.html page and link it with index
  features.html
  pricing.html
Labels: enhancement, gssoc25, level 3

#48 Update contact page
  contact.html
Labels: enhancement, gssoc25, level 3

#68 GSOC25 Add floating Back to Top button with smooth scroll
  index.html
  scripts/main.js
  styles/mainindex.css
Labels: enhancement, gssoc25, level 2

#71 Fix: Auto-comment workflow on new issues
  .github/workflows/issue-create-automate-message.yml
Labels: gssoc25, level 1

#78 feat(security): add header with navigation to security page
  security.html
Labels: enhancement, gssoc25, level 2

#108 Added some margin to togggle button to overcome the overlapping of th…
  styles/mainindex.css
Labels: enhancement, gssoc25, level 2

#111 Responsive CSS for theme toggle button & Navbar-Theme (#124)
  styles/mainindex.css
Labels: bug, gssoc25, level 2
